### ISSUE TITLE
I am a little confused

### ISSUE THREAD

**Issue by jerry1807** [Henshall/php-tinder-api#7]
Is the token obtained by phone otp is same as the facebook otp ?

also I am trying to call the function from a php form how can I obtain the token in this method

**Comment by Henshall** [comment]
I think it is the same token - but I am unsure since I have only used the phone method and not facebook.

You should be able to accept a phone number from the form and pass it to your back-end php script/file. Once its there you can include the php-tinder-api class and use the  requestCode method which will send an sms to the number provided.

**Comment by jerry1807** [comment]
Can I contact you regarding a job based on this

**Comment by jerry1807** [comment]
How can I use the form with this ?
```
<form class="actionForm" action="<?php _e( get_module_url('token') )?>" method="POST" data-redirect="<?php _e( get_module_url('index/general') )?>">
		
			<label for="Phone Number"><?php _e("Enter Phone Number ")?></label>
			<input type="text" id="facebook_id" name="facebook_id">
		

			<label for="Otp "><?php _e("Enter OTP ")?></label>
			<input type="text" id="access_token" name="access_token">
	
		
		<button type="submit"><?php _e('Submit')?></button>
	</form>
```

this is my code I am tr yign to call the request code method from your Api. Please Direct me bro

**Comment by jerry1807** [comment]
How can I use the form with this ?

<form class="actionForm" action="<?php _e( get_module_url('token') )?>" method="POST" data-redirect="<?php _e( get_module_url('index/general') )?>">
		
			<label for="Phone Number"><?php _e("Enter Phone Number ")?></label>
			<input type="text" id="number_plus" name="Phone Number ">
		

			<label for="Otp "><?php _e("Enter OTP ")?></label>
			<input type="text" id="access_token" name="access_token">
	
		
		<button type="submit"><?php _e('Submit')?></button>
	</form>
this is my code I am tr yign to call the request code method from your Api. Please Direct me bro

**Comment by Henshall** [comment]
Hello, You can contact me at https://ourdesigngroup.com if your interested in development work or consultation and I can walk you through anything you need.

I think this issue should be closed since this is related to front end work and passing data to the back end of your application. 

I hope that makes sense. 

Thanks!

**Comment by jerry1807** [comment]
exactly i will close this

**Comment by jerry1807** [comment]
Thanks for helping
